hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "e8cd685b609577ab23e2a55ec3273a1ff9475daef52f0999b2c5d27f7c795f5c"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b52cd1f4295d855882a41b5f164385e2ba460d7766a2e2e6183ef56c00c824ab"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d1dc8ac9ea0e5aed978c464ff34e460924dfc44d518eece4abbbfb9a5d49abf8"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "dcde5bfabe35341d1dedeb43ce46c4f9310c02a3ba3aad8402933a4e3bdfc491"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "51ac305aa5338daa92562c574fbf38f79cc3cc789eb390d34e7a1aed2ccee734"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "1458e4909039fdd41aeb1d7cc7c82fa6def77a48b29ab45f99a9248e05f1e8e1"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "dc8b488ec2e5320d9451e88db0c6f6e4339ad5cda64fb8d589e5a471c69ffe6a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7873ca5fa00f1d5bcc11ba839aed4866e660017f8caee9337c7dffc8682d5653"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "3a68d8f694877589b9d29bd7b44b590a123007f28142d0deed1ba34c9b90b51c"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "408bba556516e21cfa25674fabca2e1da87f7db700a7b88c2cdf1025414b39a1"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "80e52c4c76edb7e19169870e10ac16e966396e5a8f1a430ca039f52ceea9e297"
metafile = true
