hash-format = "sha256"

[[files]]
file = "config/minelp.json"
hash = "9f56866164c91a552f11dcba7097e2e184c5ad9b606f0cf2a5a73d080fc6b334"

[[files]]
file = "global_packs/required_data/CPlusCobbledAndSmoothChanges.zip"
hash = "c0946bed7e86cab95ee3cebcd013b087f21ad5798bc2ce26a2de26cab875413d"

[[files]]
file = "mods/additional-structures.pw.toml"
hash = "a676b0b14ed4ef17d47b7c073d48b2a0ed0284d27f09a6665098d43b66ccc5a3"
metafile = true

[[files]]
file = "mods/advancement-screenshot.pw.toml"
hash = "35610699676ac9c351470bce085e27ddec12d97a975237cda5a86b15be3c607c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "7916e9bf676dd9730f970893ff61fd25f43c563ff6133d1e7886366a3cd9e282"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "5ed702367e498efec1eb02046d9f0ebbb5aadff4b4cf4ee84488e62ae7829f25"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
hash = "8819e68ae91bcffd6cdee453443a8b939892a229f78cbd114e3e594faaa491ff"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "0708223179ebe2bad131cfc063dde7cf65ec355c18a3c1392646142e46ea95f3"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "112cb3b761a4ef017c2123fe61c0bcd0425d67ecbbc77ea76dd4f9c6842312bf"
metafile = true

[[files]]
file = "mods/better-potion-visuals.pw.toml"
hash = "ebeea194b3e59b0f268d7e6a7554c5d02c9be9e66f1f49d3a0e0d5d03c13c374"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "e8cd685b609577ab23e2a55ec3273a1ff9475daef52f0999b2c5d27f7c795f5c"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "5d898bbdb655828c59223382f85016f8328884b3ff176b697c51e8dedaec68c1"
metafile = true

[[files]]
file = "mods/charm-of-undying.pw.toml"
hash = "4023debbe53b41b1326ebbd477c5bafb97c3d03823cea379ee86009a801d5bf5"
metafile = true

[[files]]
file = "mods/chickensshed.pw.toml"
hash = "8bc786e062df82909ca65960da8c49469a70638587f28edbde548c47b94e1126"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "60eea1bbbf59860d54d9d66b0961e2f414586f1fbc66a416e5c02f34e883b1aa"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b52cd1f4295d855882a41b5f164385e2ba460d7766a2e2e6183ef56c00c824ab"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
hash = "9b995af454d8e7458cb2862c25f2e8c75f623aacaad97a6e810d3b9d12024394"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d1dc8ac9ea0e5aed978c464ff34e460924dfc44d518eece4abbbfb9a5d49abf8"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "dcde5bfabe35341d1dedeb43ce46c4f9310c02a3ba3aad8402933a4e3bdfc491"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "51ac305aa5338daa92562c574fbf38f79cc3cc789eb390d34e7a1aed2ccee734"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
hash = "a206bc693d41eb72f431abfc5d4556f9e9bf7f0bb6237224b750df85aeddd434"
metafile = true

[[files]]
file = "mods/consistencyplus.pw.toml"
hash = "9f8eb4c7de8c63a70721881bf949c022e3362d951230fa88bd11d0dba6e1d8f6"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2e30808f998481e8e17b995fcd74394e0a7aaace16be55a0292f3f80157df578"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "f066498a64c8a7c13dc28dda561fb4a2923da63df002e1bbbbf8f2652869cbd2"
metafile = true

[[files]]
file = "mods/corner-portal-linking.pw.toml"
hash = "8a194f2432a78eef004f6d59926719c10fdf6356bc2acf829c1a808f63ac18f7"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "1458e4909039fdd41aeb1d7cc7c82fa6def77a48b29ab45f99a9248e05f1e8e1"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "7646dd860da502a19dea0fbdd470872da374d33b0e66359fe2ed9c91a3006c0b"
metafile = true

[[files]]
file = "mods/crying-portals.pw.toml"
hash = "aecf4a777a96228ca676df16f20ec813982775c200726e440c20308cc4839ad9"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
hash = "ec0f3f834a3387266d9b8fe83112e4ce802ec6926f196e6b598dc1bf7e65c393"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "dc8b488ec2e5320d9451e88db0c6f6e4339ad5cda64fb8d589e5a471c69ffe6a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/dynamicsurroundings_remasteredfabric.pw.toml"
hash = "4d67ab760c17564b2918606dc6cd6944b2b4630c6d147c2ba8989ad932fd73f1"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "bd52ab27068961afc53efd50c527302775b87fb176d10779e0d6a0428dcc51e4"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/editsign.pw.toml"
hash = "77c7376b7c419934749cb7d7cc4821020cdbfbe96dba003505bd71ad18d76578"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "a33666d7424e8a534e9b7bf77da1d19b5091c6a4e974811f86833677a907dbbd"
metafile = true

[[files]]
file = "mods/enchantedshulkers.pw.toml"
hash = "29f6f57a4f8fe861db939f260b16c72bf22ef8e904f53bb309779475feeccabf"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "68edb9c0371e1105377db6373e7ccf09275f91cc7ca961b2915b0b32955b9558"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "b6a43638d6f3e40db516964ba9fa1dcdbe2851d3b39b1a91a977eefc7f237480"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
hash = "50677286a9f1a8f0aaf18a6d8cf41cf9a5f5efd037c57e696ef5392324393d35"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "b3e1f7b080b5c4a2e3de434a6873d84ba5bd357dff99268d45db4a79fb6d43b9"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "423581d9738b23798456b7ba021698355ef8f03cef93d8c1266102a227d9a200"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "ee9ec8acfb96b060f3caae3172651436f8388c39db630ba9a7112b8d0f290746"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "f25e49ca19098f7488d30092719c0a8e480da5f01b6e7069bf1093fea82c80a8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "3a68d8f694877589b9d29bd7b44b590a123007f28142d0deed1ba34c9b90b51c"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "0497a92235c08a5ace339102c702d17e529c0770b3a340bdecebe321e3213888"
metafile = true

[[files]]
file = "mods/gliders.pw.toml"
hash = "ed475ccacc9fd35f5240d886ba3bd926affe58159711a19a799ee37ae3fda805"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
hash = "2f3d78980ca33ab11a46413f80bcd53f7d14245759006a158b05da6d2ebee63a"
metafile = true

[[files]]
file = "mods/gui-clock.pw.toml"
hash = "d367da4333917c55330390469e9fd620fbefbc6efe54bbf1845863cdcab5e00d"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "a1f6e5c7010b82cc022a4ae37290966eff652658a0d0f6598d6519f068b659ae"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a31d322db7fc41eeb9ce86c63d5a048c334c929b6e586eefe56565cb43c3056c"
metafile = true

[[files]]
file = "mods/immersive-structures-ii.pw.toml"
hash = "3e2e2bdc9a9fe447573dcdedbeee8c1046344b7cc4ae2d8383c5e1229b57306f"
metafile = true

[[files]]
file = "mods/immersive-structures.pw.toml"
hash = "8cd263da2b2ee411248ffce02ff8653c945aa5fbd55010ef603b14e72498a329"
metafile = true

[[files]]
file = "mods/increased-rails-recipe-output.pw.toml"
hash = "1cf13c81c6ee46f890a095947734386b938a3352026749da68392d12068bd066"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "e7a7d29edcf007971a3cf62c5cb6931d040a1411d2ea2739082fe0fafda792cb"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "9ec7fac40bbe6f5e496993422b10b9df982cbf9ad5f8631f1070476cbf20b5fe"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "cdc6994dedc82cf7807f6afbdde9000cf11841c174008b2aad20f62d9b0b08c7"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "3f5a3d78357557c87f45ee3698f0178b17c85b7d5d8753013fec4b946b318926"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "33022430ccfc723fa386c77650f70b2ad987e1e68fa8986e1de0d9778fafebd7"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "d1df8e86811120c594a88895d3366d000736a6c1fad7124a72c8f05925775095"
metafile = true

[[files]]
file = "mods/jumpprooffarmland.pw.toml"
hash = "7b1e0a44b0d243b0b8d42c3bf2e42758e8d497891dec4ff546edb812f60b4fe4"
metafile = true

[[files]]
file = "mods/just-mob-heads.pw.toml"
hash = "e0a37310ea388586039b4ef1f79885931970aa505aec2215d6de95fbec319259"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "4de678c7f399c873b3ab0ee8c2085418d2379537a8d16e9a9f52d01b4abc0013"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "cfd9e5d05e671d4229d2afee38ba971004ada26cb99f41523d42a1bc1c0aacfe"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "408bba556516e21cfa25674fabca2e1da87f7db700a7b88c2cdf1025414b39a1"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "54037e4122f477f500dc3002b2f0ab9cda99d0fceb70da1d163be1afc99ec060"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "54a337d13450b35dfc931e7a5f3ed9fca1a1992ec51d3b1e4ea1cb5f7cd2d09c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "97ffbc7d0e4087777c5e3732780f01958f99d44c4f09fd534bbb8f239d4980a1"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
hash = "839816ce07c7cb38170e8be83a43bf1f4ddc439c3695da2a144b3d1017daaf9c"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
hash = "083e1237dbbc9ff8bd1ea9d4674043d964da40e0e0414830bd9a91a997a0bd28"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "90f8d140be45787ddb039f62015362d54ead182ef6c40761067db709e1d349be"
metafile = true

[[files]]
file = "mods/mooshroom-tweaks.pw.toml"
hash = "f1468e8f5402ddd2d1f26c679317e536b34ba63250353334e6accc51cfc3a90e"
metafile = true

[[files]]
file = "mods/music-maker-mod.pw.toml"
hash = "aa2e9887f3e7716b653b69c97d2a475d9be64da1a364d98cce3ea5685ffafba8"
metafile = true

[[files]]
file = "mods/myloot.pw.toml"
hash = "777a1bf2e8385c726a6d13853042bb292d40538f5db76bff26c6c135e1d0645f"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "d6a99e144be13fb3d0865925bf73357a2ff82f4114929cc2f35930eb21f3c7e9"
metafile = true

[[files]]
file = "mods/paper-books.pw.toml"
hash = "a7fabbd21e892f8cd3a0e95f1b9afffbad5eee850332dc1b11fb943717b6304a"
metafile = true

[[files]]
file = "mods/phantom-redux.pw.toml"
hash = "477697ed1df090a2b3c9e9b6aa55c8797f880dee16e047704c7817ae73a6dea3"
metafile = true

[[files]]
file = "mods/phosphor.pw.toml"
hash = "466d5892937df5aa05388291463b163b42fa454d8bfd22713484a0167ca3702d"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "c1a7bfc0cfb46224708f22bda2af3727e5c9290fa3c36454343ae7e8056e8109"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "2c595940e0a64a48d2505a2938293d22588fb53ab918c79643e23de5f43ba072"
metafile = true

[[files]]
file = "mods/projectsavethepets.pw.toml"
hash = "b4431b2a14519455d564ec3105a7a603a88f4820a12c92ab48081474a20936e6"
metafile = true

[[files]]
file = "mods/pure-discs-trails-tales.pw.toml"
hash = "1981b67a0683474dee030a2bafbb123c8a09a7b458e359a8abcd88a4869668ed"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "80e52c4c76edb7e19169870e10ac16e966396e5a8f1a430ca039f52ceea9e297"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "78fe291bc3d50234209d5b80735b469044f4d858dc8d3ba5bc38d1e098cb786f"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "7f16d61f278eb23f2778ebc55467391d06fd76a8710d5b857efb7762734fb281"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "afedc35545eb5be295caee5e0cac50de9941e4487a1a78d54ead98cc69110843"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "88c9f6366a1f91660d72f2e32c4c19fc1d8c0ac9e4843d9373b7e43a1272a46d"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "83a54931f4be77baa4a32bfb3f2b343d8d2af2efaa0aa6cf83e9a9d682cf4298"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "31b3bcbde9677f9fc1006aab482e6f43b7552146359cc4ef363e30a237d1d12b"
metafile = true

[[files]]
file = "mods/roughly-enough-professions-rep.pw.toml"
hash = "7f67f250f1ac5f71b62d9682db7e99fc1652271ad574dce12a295ab148cc8e2c"
metafile = true

[[files]]
file = "mods/roughly-enough-trades.pw.toml"
hash = "253d24d518bf1c952361a25e91d1c80d0c30f83a47c8a94a05bdf8d51a6e97a9"
metafile = true

[[files]]
file = "mods/sdlink.pw.toml"
hash = "66d8149059c590665d778d8bda09e4344a9307ca391976d43b9ae868b4ed760d"
metafile = true

[[files]]
file = "mods/serversleep.pw.toml"
hash = "18ef9ed32b347bee4e121c66c8bd88459bd21cb3c83a7d8c3f222ad9e45a67d6"
metafile = true

[[files]]
file = "mods/shulker-drops-two.pw.toml"
hash = "7a15de38822f38f9aa745dccc841f572c692f29e642b0789f944c7eb38a09798"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "442827f804bf0c72a73f4b4948875908a997821b77e35de9d4af7d37f1c7f0f1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e6153aab072571a220db10648db68e7678c1f735c5f5e8b6e8497ad5e013adc2"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/spoornpacks.pw.toml"
hash = "3abe75fd690b76a160320df05906397a7bf2091ee600f4f825127c5b6f5d05a1"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "daeec6e32a564883d796749c66e372463b2ecadf45d95e7b05f4e984cda80d91"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "70da594f4eadb175c7eedd58ec67caeffb71ac5fc8c503fcddf04e545e78e590"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "d0cd4b1f936b73cbe367ccc74c325688bb5aa1e87e41f571124a22c3b361c2c1"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "8dab797219b7e7127e1324a3e8f929d22017e90373c68aa8afda970f33b838dc"
metafile = true

[[files]]
file = "mods/switchy-inventories.pw.toml"
hash = "42e53f3f3723708716cdc6b30fd0125546b5a00c92e1334611fde2d4d2bd731f"
metafile = true

[[files]]
file = "mods/switchy-proxy.pw.toml"
hash = "81435959abd6b38b237c255de5313e9679da47d1c84ccdcb0ec30332198431d0"
metafile = true

[[files]]
file = "mods/switchy-resource-packs.pw.toml"
hash = "3644a1a2195e1c2d4354d02ef6f06bb6bdd2e7ad8e8eab82d74b661aa43819d8"
metafile = true

[[files]]
file = "mods/switchy-teleport.pw.toml"
hash = "45cfb1774eee4ece0713fa6351538bb20f6d380a8caa33cc354af825c77f2765"
metafile = true

[[files]]
file = "mods/switchy.pw.toml"
hash = "83eb3d5bad961e193f6a6339af3fc6ce18756e07341c96d14887331179f50c25"
metafile = true

[[files]]
file = "mods/switchykit.pw.toml"
hash = "899a8fd91b062153a42a7a37a86e48bc455c28b926f2a0bef6a5c6b4313091ef"
metafile = true

[[files]]
file = "mods/telo-pakola.pw.toml"
hash = "040c18c20c8d9124db8c2679799cd7871497410ab4d4332a445b6be9f563ca56"
metafile = true

[[files]]
file = "mods/tinkerers-smithing.pw.toml"
hash = "a155334f6a6c95af39e89137679527c547637454e004431d9428a44314782235"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "26d8e1910d9054354b5e8c55c97167a76a0266fe73279aa302d35d1c9a0aaf9b"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
hash = "197ad3f817c4c685915cbed15912168f780a12277ad2f558839b4154c4f6f46e"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "e4e021f4e9647d01496dfd9f4dbf77cf46575318bd54f40aac7d3b4996baecb8"
metafile = true

[[files]]
file = "mods/utility-belt.pw.toml"
hash = "3b86ae8f3808846c0ec4c96bf54eed9a704e0a92c102b3176eb795050703a4f0"
metafile = true

[[files]]
file = "mods/wandering-collector.pw.toml"
hash = "ff70792c0effb18c509f37d387a6712a15b6893e7eb898d7671b20f4b2d8756f"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "36bc57806a6d997d79767620bc3f0b019e878f337a2655b9cb98a006c4e5d2e8"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "e8036308d5fdaf3e155684892dffa19122c31745c40fbe55027a1677179263d7"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "db24b9f5262599c4a358be6e80e78a9fc0e4ad46b4dd00435aca9f76a60d7ca0"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "7ff8a4f5dc16d36c44d08439017a97006d333ca196dd4a6507d82debe9af05f5"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "4b502ea7f185b192b42c890e30b181246b341b1fcf4bd626b68c07de3cb46b19"
metafile = true

[[files]]
file = "servers.dat"
hash = "8c7524e3d6689b7c937f5f6a44608c7ad07625b700253c3167885e0d2f558785"
