name = "namako pi ma musi"
author = "jan Deni"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02ce5ee914cccfa152c8e716b3780af42aeeb9051f171973c67661e58f16079a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.3-beta.1"
