name = "namako pi ma musi"
author = "jan Deni"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20b6379296f6d1042001998d669950df7b601631faf49f5100727c94725f41fc"

[versions]
minecraft = "1.19.2"
quilt = "0.19.3-beta.1"
