name = "namako pi ma musi"
author = "jan Deni"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b8c12f18c8360b099cd10a7d6d7a85b37cfefd824e6443f9285c1cfea2e863"

[versions]
minecraft = "1.19.2"
quilt = "0.19.3-beta.1"
