name = "namako pi ma musi"
author = "jan Deni"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcc67300ab74c9fdc40c3a2bd5fc8bfc30331051a86863fdcd5bf4d1f6fc1ca3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.3-beta.1"
